### ISSUE TITLE
cost_theta_scaleが反映されない

### ISSUE THREAD

**Issue by yukizaki** [isri-aist/BaselineFootstepPlanner#3]
https://github.com/isri-aist/BaselineFootstepPlanner/blob/master/config/FootstepPlanner.yaml#L5
こちらのtheta_scaleを変更してもプランニングに反映されないようです。

theta_scaleと cost_theta_scaleが混在しているのが問題かと思います。
ひとまず、以下の1行をかえると反映されるようになりました。
https://github.com/isri-aist/BaselineFootstepPlanner/blob/master/src/FootstepEnvConfigRos.cpp#L38<https://github.com/isri-aist/BaselineFootstepPlanner/blob/master/src/FootstepEnvConfigRos.cpp#L38>
`nh.param("theta_scale", cost_theta_scale, cost_theta_scale);`

**Comment by mmurooka** [comment]
ありがとうございます．メンバ変数名とROS parameter名を一緒にするのが良いかと思い https://github.com/isri-aist/BaselineFootstepPlanner/commit/3b8d05a4adf1eb7c0a891e433e492a301654f799 のように修正しました．これで解決しているはずだと思います．
